name: llama3-8b-large-5ep-lr-5e-5
image: mosaicml/llm-foundry:2.5.1_cu124-latest
scheduling:
  priority: medium
  resumable: true
  max_retries: 2
  preemptible: false
compute:
  gpus: 64
  cluster: r15z4p1
  instance: oci.bm.gpu.h100.8
parameters:
  seed: ${variables.global_seed}
  model:
    name: hf_causal_lm
    pretrained: true
    init_device: mixed
    use_auth_token: true
    use_flash_attention_2: true
    pretrained_model_name_or_path: ${variables.model_name}
  loggers:
    wandb:
      name: ${variables.run_name}
      group: ${variables.group_name}
      project: chess-rl
  run_name: ${variables.run_name}
  callbacks:
    lr_monitor: {}
    speed_monitor:
      window_size: 10
    memory_monitor: {}
    hf_checkpointer:
      overwrite: true
      precision: float32
      save_folder: oci://mosaicml-internal-checkpoints/chuck/chess_rl/checkpoints/${variables.run_name}/
      save_interval: ${variables.save_interval}
      huggingface_folder_name: batch_{batch}
    runtime_estimator: {}
  optimizer:
    lr: ${variables.lr}
    name: decoupled_lionw
    betas:
    - 0.9
    - 0.95
    weight_decay: 0
  precision: amp_bf16
  scheduler:
    name: cosine_with_warmup
    alpha_f: 0.1
    t_warmup: 100ba
  tokenizer:
    name: ${variables.model_name}
    kwargs:
      model_max_length: ${variables.max_seq_len}
  variables:
    lr: 5.0e-05
    run_name: small_tok_${variables.group_name}_model_${variables.model_name}_dataset_${variables.data_subset}_ba_${variables.num_batches}_lr_${variables.lr}
    group_name: 12_26_sft_final
    model_name: j316chuck/Llama-3.1-8B-Instruct-Chess-128
    data_subset: large
    global_seed: 17
    max_seq_len: 8192
    num_batches: 25000
    save_interval: 5000ba
  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1
  eval_first: false
  eval_loader:
    name: finetuning
    dataset:
      split: validation
      hf_name: j316chuck/chess_rl
      shuffle: false
      hf_kwargs:
        data_dir: ${variables.data_subset}
      max_seq_len: ${variables.max_seq_len}
      packing_ratio: auto
      allow_pad_trimming: false
      decoder_only_format: true
    timeout: 0
    drop_last: true
    pin_memory: false
    num_workers: 8
    prefetch_factor: 2
    persistent_workers: true
  fsdp_config:
    mixed_precision: PURE
    state_dict_type: sharded
    limit_all_gathers: true
    sharding_strategy: FULL_SHARD
    activation_cpu_offload: false
    activation_checkpointing: true
    activation_checkpointing_reentrant: false
  max_seq_len: ${variables.max_seq_len}
  save_folder: oci://mosaicml-internal-checkpoints/chuck/chess_rl/checkpoints/${variables.run_name}
  dist_timeout: 3600
  max_duration: ${variables.num_batches}ba
  progress_bar: false
  train_loader:
    name: finetuning
    dataset:
      split: train
      hf_name: j316chuck/chess_rl
      shuffle: true
      hf_kwargs:
        data_dir: ${variables.data_subset}
      max_seq_len: ${variables.max_seq_len}
      packing_ratio: auto
      allow_pad_trimming: false
      decoder_only_format: true
    timeout: 0
    drop_last: true
    pin_memory: false
    num_workers: 8
    prefetch_factor: 2
    persistent_workers: true
  eval_interval: 20ba
  save_filename: batch_{batch}
  save_interval: ${variables.save_interval}
  log_to_console: true
  save_overwrite: false
  load_weights_only: true
  max_split_size_mb: 512
  console_log_interval: 1ba
  device_eval_batch_size: 2
  eval_subset_num_batches: 1
  global_train_batch_size: 128
  device_train_microbatch_size: 2
  save_num_checkpoints_to_keep: 1
integrations:
- integration_type: git_repo
  git_repo: j316chuck/llm-foundry
  ssh_clone: false
  git_branch: chuck/rl
  pip_install: .[gpu]
env_variables:
  AWS_PROFILE: data-force-one
  HF_HUB_ENABLE_HF_TRANSFER: '1'
command: |-
  cd llm-foundry/scripts
  export HF_HUB_ENABLE_HF_TRANSFER=1
  composer train/train.py /mnt/config/parameters.yaml
